python3-numpy: Enable vector extentions since highway pkg needs it
Fixes
| ../numpy-2.2.3/numpy/_core/src/highway/hwy/ops/rvv-inl.h:644:17: error: use of undeclared identifier '__riscv_vsetvl_e32mf2'
| ../numpy-2.2.3/numpy/_core/src/highway/hwy/ops/rvv-inl.h:644:17: error: use of undeclared identifier '__riscv_vsetvl_e32mf2'
| ../numpy-2.2.3/numpy/_core/src/highway/hwy/ops/rvv-inl.h:644:17: error: use of undeclared identifier '__riscv_vsetvlmax_e64m1'
| ../numpy-2.2.3/numpy/_core/src/highway/hwy/ops/rvv-inl.h:644:17: error: use of undeclared identifier '__riscv_vsetvl_e64m1'
| ../numpy-2.2.3/numpy/_core/src/highway/hwy/ops/rvv-inl.h:644:17: error: use of undeclared identifier '__riscv_vsetvl_e64m1'
| ../numpy-2.2.3/numpy/_core/src/highway/hwy/ops/rvv-inl.h:644:17: error: use of undeclared identifier '__riscv_vsetvl_e64m1'
| fatal error: too many errors emitted, stopping now [-ferror-limit=]

Signed-off-by: Khem Raj <raj.khem@gmail.com>