bpftrace: Fix llvm-objcopy issue and backport libbpf patches for kirkstone-clang18
Fix bpftrace do_configure failure for kirkstone-clang18:
  | CMake Error at tests/data/CMakeLists.txt:6 (find_program):
  |   Could not find LLVM_OBJCOPY using the following names: llvm-objcopy,
  |   llvm-objcopy-18, llvm18-objcopy
This error occurs because bpftrace searches for llvm-objcopy-${LLVM_VERSION_MAJOR},
expecting llvm version 18.x, while llvm-native from oe-core provides v13.0.1.
Since clang-native provides v18.1.6, switching to it resolves the issue.

While fixing this, additional libbpf compatibility issues were identified during
bpftrace compilation, requiring backporting of multiple patches to resolve:
	• Undefined BTF_KIND_ENUM64, replaced with BTF_KIND_ENUM.
	• Missing kprobe_multi in bpf_link_create_opts.
	• Undefined BPF_TRACE_KPROBE_MULTI.
	• Undefined reference to btf_is_enum64 in libbpf.so
and other related libbpf errors

Signed-off-by: Soumya Sambu <soumya.sambu@windriver.com>