jack: Use gcc to build for 32bit arches
Latest jack does not build with clang-13 for 32bit arches

| In file included from ../git/common/JackFreewheelDriver.cpp:23:
| ../git/common/JackEngineControl.h:67:5: error: requested alignment is less than minimum alignment of 8 for type 'Jack::JackTransportEngine'
|     alignas(UInt32) JackTransportEngine fTransport;
|     ^
| ../git/common/JackEngineControl.h:89:5: error: requested alignment is less than minimum alignment of 8 for type 'Jack::JackFrameTimer'
|     alignas(UInt32) JackFrameTimer fFrameTimer;
|     ^
| 2 errors generated.

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit e4978cc3ef008c69a49295dc8bc997b8291f6b11)