gdb-cross,gnu-efi,systemtap,tcp-wrappers: Use gcc only for now
gdb-cross is added since it looks for a gcc for clang frontend as a
result it finds gcc in /usr/lib/gcc .. and OE's configure QA check sees
this as if the build referenced into hosts /usr/lib and bails out.

systemtap uses a lot of nested inlines which is unsupported by clang,
time permitting this should be cleaned

gnu-efi says
error: the 'sse' unit is not supported with this instruction set

tcp-wrappers fails with
fix_options.c:66:2: error: non-void function 'fix_options' should return a value [-Wreturn-type]
        return;
        ^
fix_options.c:109:3: error: non-void function 'fix_options' should return a value [-Wreturn-type]
                return;

Signed-off-by: Khem Raj <raj.khem@gmail.com>