mongodb: Use llvm runtime when using clang
Fixes linker errors like
src/mongo/platform/overflow_arithmetic.h:63: error: undefined reference to '__mulodi4'
src/mongo/platform/overflow_arithmetic.h:63: error: undefined reference to '__mulodi4'
src/mongo/platform/overflow_arithmetic.h:63: error: undefined reference to '__mulodi4'
src/mongo/platform/overflow_arithmetic.h:63: error: undefined reference to '__mulodi4'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 0c02a3503f6b240ec34c68bc9c00407bae2b0fa4)