Pass -Wno-error=unused-command-line-argument to clang
We can get past the errors due to -Werror when unused cmdline
options appear on compiler cmdline

e.g.

error: argument unused during compilation: '-pie'

Signed-off-by: Khem Raj <raj.khem@gmail.com>