compiler-rt-sanitizers: fix directory name on do_install when removing liborc_rt
on do_install() the directory containing the .a files is renamed from
${MAJOR_VER} to ${MAJOR_VER}.${MINOR_VER}.${PATCH_VER} but the rm
command below fails to account for that rename and tries to delete
the file on a non-existing directory after the rename.

This causes later a conflict when creating the rootfs or populating the SDK:
 - do_populate_sdk failed with exit code '1'
   Error: Transaction test error:
     file /usr/lib/clang/20.1.1/lib/linux/liborc_rt-aarch64.a from install of
     compiler-rt-sanitizers-staticdev-20.1.1-r0.cortexa72 conflicts with file
     from package compiler-rt-staticdev-20.1.1-r0.cortexa72

Signed-off-by: Carlos Alberto Lopez Perez <clopez@igalia.com>