Revert "clang: Do not provide llvm-native implicitly"
This reverts commit 384e8d169a2c408e2cef03ea2deb88fb82058011.

The original commit removed the implicit PROVIDES declarations for llvm,
llvm-native, and nativesdk-llvm from the clang recipe.

However, this change breaks builds in kirkstone-clang18 environments, where
mesa and lib32-llvm expect these to be provided by clang:

- Mesa fails due to missing providers for llvm18.1.6 and nativesdk-llvm18.1.6.
- lib32-llvm 13.0.1 fails on ARM BSPs with the following error, falling back to
  the core layer's outdated LLVM:

    error: 'RegVT' was not declared in this scope

This commit was backported from scarthgap, but it is incompatible with oe-core
expectations in the kirkstone branch. Reverting it restores compatibility.

Signed-off-by: Haixiao Yan <haixiao.yan.cn@windriver.com>