clang: scan-build-py: respect LLVM_LIBDIR_SUFFIX like other tools do
* other libraries are installed in 'lib64' or 'lib32' based on
  LLVM_LIBDIR_SUFFIX value, but libscanbuild files were always
  installed in 'lib'

* fixes:
  ERROR: QA Issue: lib32-clang: Files/directories were installed but not shipped in any package:
    /usr/lib/libscanbuild
    /usr/lib/libscanbuild/intercept.py
    /usr/lib/libscanbuild/analyze.py
    /usr/lib/libscanbuild/clang.py
    /usr/lib/libscanbuild/report.py
    /usr/lib/libscanbuild/arguments.py
    /usr/lib/libscanbuild/shell.py
    /usr/lib/libscanbuild/compilation.py
    /usr/lib/libscanbuild/__init__.py
    /usr/lib/libscanbuild/resources
    /usr/lib/libscanbuild/resources/sorttable.js
    /usr/lib/libscanbuild/resources/selectable.js
    /usr/lib/libscanbuild/resources/scanview.css
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
  lib32-clang: 13 installed and not shipped files. [installed-vs-shipped]

  e.g. in multilib build where libdir is set to /usr/lib32 or /usr/lib64.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>