recipes: Link with libgcc when building static versions on arm
since llvm libunwind does not provide all the symbols that
glibc/libpthread expects when doing static linking it fails with
some undefined symbols e.g.

/usr/src/debug/glibc/2.29-r0/git/nptl/unwind.c:121: undefined reference to `_Unwind_ForcedUnwind'

which is found in libgcc_s.so, ideally one day clang unwind library
should get there

this is only an issue on glibc, musl works ok

Signed-off-by: Khem Raj <raj.khem@gmail.com>