android-tools-conf: remove PACKAGE_ARCH = MACHINE_ARCH
android-tools inherits the native class, and RDEPENDS on android-tools-conf.
This line causes an error when trying to build android-tools-native:

"""
ERROR: Required build target 'android-tools-native' has no buildable providers.
Missing or unbuildable dependency chain was: ['android-tools-native', 'clang-native-x86_64']
"""

Signed-off-by: Etienne Cordonnier <ecordonnier@snap.com>