bpftool: Use gcc instead of clang compiler
While compiling bpftool with clang, it fails with below error:
| error: no member named 'id' in 'struct bpf_link'
|           return BPF_CORE_READ((struct bpf_link *)ent, id);

bpftool is kernel tool to inspect and manipulate eBPF programs and maps.
And kernel is built using GCC by default. Maintaining compatibility with
Clang is an ongoing challenge, and using Clang solely for building bpftool
is ineffective unless the entire kernel is compiled with Clang.

Hence, updated TOOLCHAIN of bpftool to gcc.

Signed-off-by: Deepak Rathore <deeratho@cisco.com>