clang: Upgrade to latest tip of master 3.7
Add fix for missing is_pod definition
and additionally fix packaging for nativesdk

PACKAGE_DEBUG_SPLIT_STYLE_class-nativesdk = "debug-without-src"
Fixes errors like

ERROR: debugedit failed with exit code 256 (cmd was
'/mnt/home/kraj/work/angstrom/build/tmp-angstrom-glibc/sysr
oots/x86_64-linux/usr/lib/rpm/bin/debugedit' -b
'/mnt/home/kraj/work/angstrom/build/tmp-angstrom-glibc/work/x86
_64-nativesdk-angstromsdk-linux' -d '/usr/src/debug' -i -l
'/mnt/home/kraj/work/angstrom/build/tmp-angstrom-gli
bc/work/x86_64-nativesdk-angstromsdk-linux/nativesdk-clang/3.7.0-r0/debugsources.list'
'/mnt/home/kraj/work/ang
strom/build/tmp-angstrom-glibc/work/x86_64-nativesdk-angstromsdk-linux/nativesdk-clang/3.7.0-r0/package/usr/loc
al/oecore-x86_64/sysroots/x86_64-angstromsdk-linux/usr/lib/libLTO.so.3.7.0svn'):
/mnt/home/kraj/work/angstrom/build/tmp-angstrom-glibc/sysroots/x86_64-linux/usr/lib/rpm/bin/debugedit:
canonica
lization unexpectedly shrank by one character

see
http://lists.openembedded.org/pipermail/openembedded-core/2013-April/077746.html

Signed-off-by: Khem Raj <raj.khem@gmail.com>