bcc: biosnoop: Fix failing to attach to trace_req_completion
/usr/share/bcc/tools/biosnoop
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
File "/usr/share/bcc/tools/biosnoop", line 162, in <module>
b.attach_kprobe(event="blk_account_io_completion",
File "/usr/lib64/python3.8/site-packages/bcc/_init_.py", line 660, in attach_kprobe
raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'trace_req_completion' to kprobe b'blk_account_io_completion'

The kernel function "blk_account_io_completion" is not available anymore
as attach point of Kprobe as of kernel version 5.8.0. Therefore, after
discussions, we decided to use function "blk_account_io_done" instead in
every kprobe attachment to "blk_account_io_completion".

Signed-off-by: He Zhe <zhe.he@windriver.com>