mybw: Use libgcc to link on x86_64
Fixes
x86_64-yoe-linux-ld: /usr/src/debug/glibc/2.36-r0/stdio-common/printf_fphex.c:198: undefined reference to `__letf2'
since compiler-rt does not provide the 'tf' functions

Signed-off-by: Khem Raj <raj.khem@gmail.com>