clang: Use git suffix instead of svn
src uri has long moved to git, and that is also being used as solib suffix

Fixes packaging errors
ERROR: clang-10.0.0-r0 do_package_qa: QA Issue: libclang rdepends on clang-dev [dev-deps]
ERROR: clang-10.0.0-r0 do_package_qa: QA Issue: clang rdepends on clang-dev [dev-deps]

Signed-off-by: Khem Raj <raj.khem@gmail.com>