bcc: move to the right dynamic-layer
* it depends not only on meta-oe, but on meta-python as well
  and because meta-python depends on meta-oe, we can enable this
  when ever meta-python is included

* fixes:
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'python3-pyroute2' (but /OE/build/oe-core/meta-clang/dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.28.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-pyroute2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-pyroute2']
ERROR: Nothing RPROVIDES 'python3-netaddr' (but /OE/build/oe-core/meta-clang/dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.28.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-netaddr' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-netaddr']
ERROR: Nothing RPROVIDES 'bcc-dev' (but /OE/build/oe-core/meta-clang/dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.28.0.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'bcc-dev'
NOTE: Runtime target 'bcc-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['bcc-dev']
ERROR: Nothing RPROVIDES 'bcc' (but /OE/build/oe-core/meta-clang/dynamic-layers/openembedded-layer/recipes-devtools/bcc/bcc_0.28.0.bb RDEPENDS on or otherwise requires it)
No eligible RPROVIDERs exist for 'bcc'
NOTE: Runtime target 'bcc' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['bcc']