libbpf: Backport bpf_btf_get_info_by_fd
bcc v0.29.1 depends on bpf_btf_get_info_by_fd, which was introduced in libbpf v1.2.0.

Since meta-oe kirkstone provides libbpf v0.7.0, this function was missing,
resulting in a linker error in the bcc build:
    undefined reference to `bpf_btf_get_info_by_fd`

This patch backports the necessary commit from libbpf v1.2.0 to v0.7.0,
allowing bcc v0.29.1 to build successfully.

Upstream patch:
https://github.com/libbpf/libbpf/commit/30f6bc3c0a296638e3b6930dbcff6f1547f13997

Signed-off-by: Soumya Sambu <soumya.sambu@windriver.com>