ncurses: fix build errors in some clang configurations
ncurses' configure script strips the arguments from $CC when checking
if -c and -o can be used together. Clang then doesn't have a default
sysroot argument to use, so it checks the host for the existence of
certain feature headers in libc. These checks fail, and it assumes
that clang can't handle -o and -c together.

Example config.log snippet:

configure:2524: checking whether arm-poky-linux-gnueabi-clang understands -c and -o together
configure:2540: arm-poky-linux-gnueabi-clang -c conftest.c -o conftest2.o >&5
In file included from conftest.c:1:
In file included from /usr/include/stdio.h:27:
In file included from /usr/include/features.h:399:
/usr/include/gnu/stubs.h:7:11: fatal error: 'gnu/stubs-32.h' file not found
# include <gnu/stubs-32.h>
          ^
1 error generated.
configure:2543: $? = 1
configure:2562: result: no

Signed-off-by: Daniel McGregor <daniel.mcgregor@vecima.com>