lldb: Disable builds for ppc32
ppc32 build fails, disable for now

NativeThreadLinux.cpp:(.text._ZN12lldb_private13process_linux17NativeThreadLinuxC2ERNS0_18NativeProcessLinuxEy+0x84): undefined reference to `lldb_private::process_linux::NativeRegisterContextLinux::CreateHostNativeRegisterContextLinux(lldb_private::ArchSpec const&, lldb_private::process_linux::NativeThreadLinux&)'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 8efb230dd73cfd19e575ff42fea979d977b05c97)