python3-pyside6: Remove due to being missing from meta-qt6 dev
The recipe being bbappended is not supported in meta-qt6 until later in a
stable versions life cycle.  This has the effect that in the most recent
version branches (6.10 as of this commit) does not have the required recipe
to bbappend, and dev will never have the recipe.  This causes a parsing
error when using these more up to date branches:

ERROR: No recipes in default available for:
  .../meta-clang/dynamic-layers/qt6-layer/recipes-qt/qt6/python3-pyside6_%.bbappend

Given this, we should drop this bbappend and try to address the build
failure in world another way.

Signed-off-by: Ryan Eatmon <reatmon@ti.com>