clang: Switch c++ default to gnu++14 standard
Using cmdline options -std doesnt always work e.g. boost
where it uses c++ driver (clang++) to invoke compilation
but then passes '-x c' to choose the language for compilation

Which ends in errors like below

error: invalid argument '-std=c++14' not allowed with 'C'

Therefore change the defaults in driver itself to use gnu++14
which is default with g++ from gcc7+ too.

Signed-off-by: Khem Raj <raj.khem@gmail.com>