upgrade of android-tools to 10.0.0.r36
An older version is present in the meta-oe layer.
Took the old recipe and adapted it in the following way:

--Deleted all the old patches that were applicable for
old version.

--Used all the makefiles that come with the new version
directly from the source code, just modifying them
to install output to a specific folder as below

a)added rules_yocto.mk that will mimic the debian/rules
b)modified the makefiles of the components to output to
a common dir.
c)
Built boringssl crypto with the option -DOPENSSL_NO_ASM
to solve the below errors

 libcrypto.so.0: undefined reference to `aes_hw_encrypt'
 libcrypto.so.0: undefined reference to `aes_hw_set_encrypt_key'
 libcrypto.so.0: undefined reference to `gcm_gmult_v8'
 libcrypto.so.0: undefined reference to `gcm_init_v8'
 libcrypto.so.0: undefined reference to `sha256_block_data_order'
 libcrypto.so.0: undefined reference to `aes_hw_ctr32_encrypt_blocks'
 libcrypto.so.0: undefined reference to `aes_hw_cbc_encrypt'
 libcrypto.so.0: undefined reference to `vpaes_decrypt'
 libcrypto.so.0: undefined reference to `vpaes_encrypt'
 libcrypto.so.0: undefined reference to `gcm_gmult_neon'
 libcrypto.so.0: undefined reference to `sha1_block_data_order'
 libcrypto.so.0: undefined reference to `sha512_block_data_order'
 libcrypto.so.0: undefined reference to `gcm_init_neon'
 libcrypto.so.0: undefined reference to `aes_hw_set_decrypt_key'
 libcrypto.so.0: undefined reference to `vpaes_set_decrypt_key'
 libcrypto.so.0: undefined reference to `gcm_ghash_neon'
 libcrypto.so.0: undefined reference to `bn_mul_mont'
 libcrypto.so.0: undefined reference to `aes_hw_decrypt'
 libcrypto.so.0: undefined reference to `gcm_ghash_v8'
 libcrypto.so.0: undefined reference to `vpaes_cbc_encrypt'
 libcrypto.so.0: undefined reference to `ChaCha20_ctr32'
 libcrypto.so.0: undefined reference to `vpaes_ctr32_encrypt_blocks'
 libcrypto.so.0: undefined reference to `vpaes_set_encrypt_key'

 Attention : https://github.com/grpc/grpc/issues/9440

d) compiled android compatible version of libunwind to be used
to build libbacktrace
e) REQUIRES meta-selinux for libselinux, thus added it to
BBFILES_DYNAMIC of this layer.
f) checked compilation and packaging for for x86_64 and aarch64
g) UNTESTED android-tools-adbd.service , couldn't find how to build adbd
that is needed by the service with the new version of android-tools. At
present the service is still packaged but may not work.
h) tested the adb and fastboot on the core-image-minimal by including
the android-tools in the image and ran the commands with 'help'

Signed-off-by: Nisha Parrakat <Nisha.Parrakat@kpit.com>
Signed-off-by: Nisha Parrakat <nishaparrakat@gmail.com>