bpftrace: fix an intermitent compile failure
A missing dependency causes intermitent compile failure:
git/src/functions.h:9:10: fatal error: location.hh: No such file or directory
    9 | #include "location.hh"

This location.hh is generated by target parser

Signed-off-by: Changqing Li <changqing.li@windriver.com>